version: "3.8"
services:
  tts:
    build: .
    image: persian-tts:latest
    container_name: persian-tts
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=facebook/mms-tts-fas
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
